[BUGFIX] fstring and dataclass generation (#1481)
* BugFix: log message is not showing minutes

Introduced in 30f5a9e1, the f-string identifier was missing for the log
message. This was visible in the logs of #1454

Issue #1454

* BugFix: MakeMKVErrorMessage with dataclass input

Error Messages were not created properly. Log Messages would show en
error like the following:

```
[2025-07-23T135203] CRITICAL ARM: makemkv.read_error Error 'Internal error - Operation result is incorrect (132)' occurred while reading 'BD-RE PIONEER BD-RW   BDR-UD04 1.14 CKDL511618WL' at offset '524288'
[2025-07-23T145124] ERROR ARM: arm_ripper.rip_visual_media MakeMKV did not complete successfully.  Exiting ARM! Error: arm.ripper.makemkv.MakeMKVErrorMessage() argument after * must be an iterable, not MakeMKVMessage
[2025-07-23T145124] ERROR ARM: main.<module>
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/arm_ripper.py", line 56, in rip_visual_media
    makemkv_out_path = makemkv.makemkv(job)
  File "/opt/arm/arm/ripper/makemkv.py", line 691, in makemkv
    makemkv_backup(job, rawpath)
  File "/opt/arm/arm/ripper/makemkv.py", line 606, in makemkv_backup
    collections.deque(run(cmd, OutputType.MSG), maxlen=0)
  File "/opt/arm/arm/ripper/makemkv.py", line 1094, in run
    msg_type, data = parse_line(line)
  File "/opt/arm/arm/ripper/makemkv.py", line 478, in parse_line
    message = MakeMKVOutputChecker(data).check()
  File "/opt/arm/arm/ripper/makemkv.py", line 1016, in check
    return self.read_error()
  File "/opt/arm/arm/ripper/makemkv.py", line 1041, in read_error
    return MakeMKVErrorMessage(*self.data)
TypeError: arm.ripper.makemkv.MakeMKVErrorMessage() argument after * must be an iterable, not MakeMKVMessage
```